# docker-compose.yml

services:
  k6:
    image: grafana/k6:latest
    volumes:
      - ./scripts:/scripts
    entrypoint: ""
    #command: ["k6", "run", "/scripts/signLoginScenario.js"]
    command: ["k6", "run", "/scripts/test.js"]
    #command: ["k6", "run", "/scripts/one_scenario.js"]